name: Comment on PR

on: pull_request

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            context.pulls.createReview({
              pull_number: 14,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'thanks'
              event: 'REQUEST_CHANGES'
              comments: [
                {
                  path: gitlab/workflows/comment_pr.yml,
                  line: 1,
                  body: 'thanks'
                }
            })
