on: [push, pull_request]
name: Main
jobs:
  phpinsights:
    name: PHP-Insights
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP-Insights
        uses: docker://tienvx/phpinsights-action
        with:
          args: "-v --min-quality=70 --min-complexity=70 --min-architecture=50 --min-style=80"
