name: PHP Rest

# Controls when the action will run. 
on: ['push','pull_request']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP Lint
        uses: michaelw90/PHP-Lint@2.1.0
